tle: string;
status: boolean;
u;
pdatedAt: DDte;
toggleStatus();
;
();
toggleStatus;
i;
deleteT: numbeTodoItemInterfaceTodoItemInterface;
module.exports = toDoInterface;
;
TodoItemToArray < string > rray < string > le;
string;
addTaskaTodoItemTodoItemdd;
listAllTaskslnaskdTodoItemTodoItemmber;
addTask(TodoItem);
number;
addTask(TodoItem);
number;
TaskedAt: Date;
TodoListInterfaceTodoListInterface;
mod;
ule.exports = toDoInterface;
